name: Build scripts

on:
    push:
        branches:
            - master
            - node

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Yarn install and build && Replace Workers' id
              run: |
                  yarn
                  yarn run build:rollup
                  sed -i 's/<YOUR_ID>/${{ secrets.CF_KV_ID }}/g' apps/cfworkers/wrangler.toml
                  sed -i 's/["*"]/${{ secrets.CF_ENV_WORKERS_ALLOW_ORIGIN }}/g' apps/cfworkers/wrangler.toml
            # - name: Upload dist
            #   uses: actions/upload-artifact@v3.1.2
            #   with:
            #       name: 'dist'
            #       path: dist
            - name: Upload browser script
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: 'archive_browser.js'
                  path: dist/archiver/archive_browser.js
            - name: Upload node script
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: 'archive_node.js'
                  path: dist/archiver/archive_node.js
            - name: Upload online backend
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: 'app_online.js'
                  path: dist/backend/app_online.js
            - name: Deploy to workers
              uses: cloudflare/wrangler-action@2.0.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  workingDirectory: 'apps/cfworkers'
